### ISSUE TITLE
Docker dies on `v0.1.4-ubuntu.24.04` release

### ISSUE THREAD

**Issue by lizziemac** [borgesnotes/pishrink-docker#10]
Hi there! I just started looking into your handy tool! I've gotten the `v0.1.4` image to successfully compress an image, however the latest Docker image `v0.1.4-ubuntu.24.04` causes Docker to stop/die completely. Not entirely sure what's going on there but figured you should know.  

I'm on MacOS Sonoma 14.4.1, Apple M2 Max

**Comment by borgesnotes** [comment]
Hey @lizziemac, 

Thank you for sharing your feedback on the new version `v0.1.4-ubuntu.24.04`. I'll test it on a new MacBook to investigate further. 

Best, Borges

**Comment by vbxx0** [comment]
> Hey @lizziemac,
> 
> Thank you for sharing your feedback on the new version `v0.1.4-ubuntu.24.04`. I'll test it on a new MacBook to investigate further.
> 
> Best, Borges

Any news?

**Comment by borgesnotes** [comment]
@lizziemac I just updated the Docker build process to ARM. Could you try updating the Docker image and checking it out again? `docker pull borgesnotes/pishrink`

**Comment by borgesnotes** [comment]
@lizziemac Have you checked the latest version? Is it working for you?

**Comment by TiborUdvari** [comment]
I had the exact same problem but in reverse, I'm using an Intel Mac and with the new version I get `No matching manifest for linux/amd64 in the manifest list entries `. Version `0.1.4` did the job for me

**Comment by borgesnotes** [comment]
@TiborUdvari thank you for your feedback! I see I need to compile two Docker Image versions, one for x86-64 Intel machines and another for ARM.

**Comment by TiborUdvari** [comment]
Just mentioning it in case anybody else has this issue. Thanks anyway your image saved me a lot of time.

**Comment by lizziemac** [comment]
Sorry for the late reply @borgesnotes, I just tested now and it appears to work on ARM! Thanks!
