### ISSUE TITLE
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by jpara** [borgesnotes/pishrink-docker#9]
Hi,

I get the warning: "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

any chance I can be used on a Mac M2 silicon?
Thank you

**Comment by borgesnotes** [comment]
Hey @jpara, are you trying to compile the Docker Image?

If yes, try to add `--platform linux/x86_64 `, something like:

```bash
docker build -t imagename --platform linux/x86_64 .
```
